name: CustomAlertsExample
main: CustomAlertsExample\Example
version: 1.2
api: [1.12.0]
depend: [CustomAlerts]
load: STARTUP
author: EvolSoft
description: CustomAlerts API implementation example 
website: http://www.evolsoft.tk
